apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
  labels:
    app: flight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - name: flight
          image: user16.azurecr.io/flight:latest
          ports:
            - containerPort: 8080
          env:
            - name: FLIGHT_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                    name: config-flight
                    key: FLIGHT_LOG_LEVEL
