apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: reservation
          image: user16.azurecr.io/reservation:latest
          ports:
            - containerPort: 8080
          resources: #cpu
            requests:
              cpu: "200m"
